version: '3.8'
 
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_antonio
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=antonio1234
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
 
volumes:
  mongo_data:
